inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Style/Documentation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Metrics/LineLength:
  Max: 150

Layout/TrailingWhitespace:
  Enabled: false
