#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/lib')
require 'prelude'
require 'example_runner'

ExampleRunner.new.run(ARGV)
